### ISSUE TITLE
关于CON1 引脚引出问题

### ISSUE THREAD

**Issue by HanfG** [peng-zhihui/Peak#16]
MCU的 GPIO5, GPIO10, GPIO19, GPIO32, GPIO33 五个引脚由CON1引出，其中GPIO32, 33已被I2C总线使用，目前线上有MPU6050，引出可以用于I2C 设备扩展；其余3个IO引脚应该是用于普通IO扩展吧，我看到芯片的GPIO9目前是悬空状态，是不是可以考虑用GPIO9替换GPIO5吗？这样可以实现MCU的UART 1信号引出 增强扩展性，也可以避免意外情况下GPIO5拉低导致MCU无法正常启动。
![image](https://user-images.githubusercontent.com/22571282/139645931-276ccd6e-4e01-4fe1-b18b-1da8b73fb1e3.png)

**Comment by peng-zhihui** [comment]
esp32是带gpio-matrix的，差不多所有引脚都能自由映射



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: HanfG ***@***.***&gt;
发送时间: 2021年11月1日 16:47
收件人: peng-zhihui/Peak ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[peng-zhihui/Peak] 关于CON1 引脚引出问题 (Issue #16)





 
MCU的 GPIO5, GPIO10, GPIO19, GPIO32, GPIO33 五个引脚由CON1引出，其中GPIO32, 33已被I2C使用，目前线上由MPU6050，引出可以用于I2C 设备扩展；其余3个IO引脚应该是用于普通IO扩展吧，芯片的GPIO9目前是悬空状态，可以考虑用GPIO9替换GPIO5吗？这样可以实现MCU的UART 1信号引出 增强扩展性，也可以避免意外情况下GPIO5拉低导致MCU无法正常启动。
 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HanfG** [comment]
好的，学到了，感谢> esp32是带gpio-matrix的，差不多所有引脚都能自由映射
